### ISSUE TITLE
Unexpected input(s) 'branch'

### ISSUE THREAD

**Issue by stiwwelll** [Bhacaz/checkout-files#15]
Hey there,

I've been trying to pass a `branch` value to my action and get the following warning:

```
Warning: Unexpected input(s) 'branch', valid inputs are ['files', 'token']
Run Bhacaz/checkout-files@v1
  with:
    token: ***
    files: es_scripts content .env.example
    branch: name/id/name
```

Is it possible that there are issues with branches including special characters like `/`

Thanks a lot for helping out

**Comment by Bhacaz** [comment]
Hi, @stiwwelll the `branch` input is not available for [`v1`](https://github.com/Bhacaz/checkout-files/tree/v1). 

I realize that the README suggest that, I'm sorry change that, maybe do a `v2` which will include the `branch` input.

For now you can use `Bhacaz/checkout-files@master` or the currant master commit to be sure to not be impacted to breaking change. `Bhacaz/checkout-files@2fe7bfc25ef77a8e4f5e4be4a47cec9528fe37e4`

**Comment by stiwwelll** [comment]
Hey @Bhacaz ,

Thanks so much for the prompt reply. You are a star. It works like a charm now!
