### ISSUE TITLE
Pull files/folder from specific branch

### ISSUE THREAD

**Issue by keunes** [Bhacaz/checkout-files#8]
Hello,

Via https://github.com/actions/checkout/issues/483 I arrived here. I'm interested in pulling (checking out) a specific file from another branch. But in the instructions I don't see anywhere how to specify the branch to pull from.

If I already checked out the main branch, can I then pull specific files from another branch (in the same repo) using this action? If so, how could I do that?

(I tried following [these instructions](https://clubmate.fi/git-checkout-file-or-directories-from-another-branch) but they don't work in an action:)
![afbeelding](https://user-images.githubusercontent.com/11229646/147455132-535ab960-fc37-4887-b32c-e784a4e07673.png)

**Comment by sun** [comment]
https://github.com/Bhacaz/checkout-files/pull/6 addresses this.

You may try using our fork https://github.com/makers99/checkout-files in the meantime.
```yaml
        uses: makers99/checkout-files@v1.1.0
```
